### ISSUE TITLE
Upgrade Axios to ^0.19.1 to support http proxy natively

### ISSUE THREAD

**Issue by kenime** [watson-developer-cloud/node-sdk#1016]
As mentioned in some closed issues (e.g. #900), this library doesn't support http proxy natively due to some compatibility issue in axios 0.18.0, and some additional code on is required to establish a https over http tunnel.

This compatibility issue is fixed (axios/axios#959) and merged in 0.19.0, hence I would propose updating the dependency to reduce customising effort.

**Comment by germanattanasio** [comment]
@kenime why don't you write a PR and we can take it from there

**Comment by kenime** [comment]
sure, PR on the way

**Comment by dpopp07** [comment]
@kenime Thanks for opening the issue. As you probably remember from [this PR](https://github.com/IBM/node-sdk-core/pull/39), we are unwilling to upgrade to `0.19.x` until we have a major release, since they seem to have made breaking changes.

We do want to upgrade at some point so I will leave this issue open for tracking. That said, I am going to close the PR for now.
