### ISSUE TITLE
Improve error handling and reporting for WebSocket recognize and synthesize streams

### ISSUE THREAD

**Issue by jfmartinez** [watson-developer-cloud/node-sdk#1028]
Hello,

Wanted to ask if its possible to improve the error handling of the SDK for the websocket recognize and synthesize streams.

Using the following example:

```javascript
const fs = require('fs');
const TextToSpeechV1 = require('ibm-watson/text-to-speech/v1');
const { IamAuthenticator } = require('ibm-watson/auth');
const { BasicAuthenticator } = require('ibm-watson/auth');
const textToSpeech = new TextToSpeechV1({
  authenticator: new BasicAuthenticator({ username: 'apikey', password: '<apikey>' }),
  url: '<url>'
});

const params = {
  text: 'Hello, I am Allison!',
  voice: 'en-US_AllisonVoice', // Optional voice
  accept: 'audio/wav'
};

const synthStream = textToSpeech.synthesizeUsingWebSocket(params);
synthStream.pipe(fs.createWriteStream('./audio.wav'));
synthStream.on('error', (error) => {
	console.log(error.event);
});

synthStream.on('close', console.log);
```

If I specify an incorrect API Key, change a letter - I would expect to get a `401 Status Code` as the reason for the connection error. But this is what I receive:

```javascript
_Event {
  type: 'error',
  isTrusted: false,
  _yaeti: true,
  target: W3CWebSocket {
    _listeners: {},
    addEventListener: [Function: _addEventListener],
    removeEventListener: [Function: _removeEventListener],
    dispatchEvent: [Function: _dispatchEvent],
    _url: 'wss://api.us-south.text-to-speech.test.watson.cloud.ibm.com/instances/5de5182d-1f0c-4ee3-8a16-b6120a623a2e/v1/synthesize?voice=en-US_AllisonVoice',
    _readyState: 3,
    _protocol: undefined,
    _extensions: '',
    _bufferedAmount: 0,
    _binaryType: 'arraybuffer',
    _connection: undefined,
    _client: WebSocketClient {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      config: [Object],
      _req: null,
      protocols: [],
      origin: null,
      url: [Url],
      secure: true,
      base64nonce: 'XXXX'
    },
    onopen: [Function],
    onmessage: [Function],
    onerror: [Function],
    onclose: [Function]
  },
  cancelable: true,
  stopImmediatePropagation: [Function]
}
```

There aren't any errors that would help the user debug the root cause of the issue, just a blank connection error. I suspect the issue is because the underlying websocket library doesn't report the exact error: https://github.com/theturtle32/WebSocket-Node

Is there a possibility to improve the error handling experience of the SDK when using the websocket based APIs?

**Comment by dpopp07** [comment]
@jfmartinez What version of the SDK are you using? I just tried to reproduce your error by changing the API key (using almost your exact code otherwise) and I got the following error:

```
Bad Request: Access is denied due to invalid credentials.
```

**Comment by jfmartinez** [comment]
@dpopp07 I'm using version `5.4.0` of the SDK, Node.js: `v12.14.1`

**Comment by dpopp07** [comment]
Okay. I am using the same version of both the SDK and Node but I am unable to reproduce your issue. In fact, I don't even get an `event` field on the error object - it prints `undefined`.

I get more error information by printing the whole error or by printing `error.message`, which is the field the usually carries the summary of what actually went wrong.

Another thing that is causing issues for me is this line: `synthStream.on('close', console.log);`. Even for a successful transcription, that causes an error: `1006 Socket Error: undefined EPIPE`.

I would change that code so that you control the callback method passed into the event handler:
```js
synthStream.on('close', () => {
  console.log('closed');
});
```

**Comment by jfmartinez** [comment]
When I use the `IamAuthenticator` as the authentication method, I do get the error you're referring to: `Bad Request: Access is denied due to invalid credentials.`. Are you using the exact same code and still get different results?

**Comment by dpopp07** [comment]
Ah yes, my apologies. I believe I misunderstood the question. I am able to reproduce your results using the `BasicAuthenticator`.

The reason for this is, as you expected, using the `IamAuthenticator` we actually make the token request before the WebSocket connection is ever opened. The error for the token request is handled by the usual SDK mechanics and we get the error.

Using the `BasicAuthenticator`, the connection is attempted with the bad credentials and the WebSocket throws the error. All it returns is the `event` field (that you were printing), which is not very helpful.

It's not just the libraries fault - that's all the information that the underlying connection provides. We provide the message `WebSocket connection error` to state that the error was in the connection itself. This usually means a credentials problem - other errors will usually be caught by a different part of the code.

There's really not much we can do about what the connection returns. What I can do is update the default message for a connection failure to say something like `Failed to make WebSocket connection. Check your credentials.` since we know it is likely a credentials problem (although we can't be 100% sure).

How does this solution sound to you?

**Comment by jfmartinez** [comment]
Gotcha, I think its a problem with the underlying WebSocket library that doesn't propagate the error correctly. 

I'm OK with leaving it generic for now. I was thinking about opening an issue with the underlying WebSocket library (looks like https://github.com/theturtle32/WebSocket-Node), 

Seems to be an issue with error handling in that library, ex: https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketClient.js#L227 and then https://github.com/theturtle32/WebSocket-Node/blob/master/lib/W3CWebSocket.js#L58 (error is ignored)

Maybe its an intentional behavior?

**Comment by dpopp07** [comment]
Hmm, that's interesting. Perhaps it is intentional, although I'm not sure what the reasoning would be. Let me know if you do open an issue there and I'll follow along

**Comment by jfmartinez** [comment]
Meant to get back to this, I was reading through the issues in the websocket-node repo, looks like its meant to work as intended per the W3CSpecification (meant for web pages): https://github.com/theturtle32/WebSocket-Node/issues/198#issuecomment-111325618

I think the only way to get more error information would be to use the other client in that library: [WebSocketClient](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md)

Or use another Node.JS Library for Websockets i.e: https://github.com/websockets/ws

Thanks!
