### ISSUE TITLE
Piping entire json result of Watson Speech

### ISSUE THREAD

**Issue by vondiplo** [watson-developer-cloud/node-sdk#253]
I'd like to be able to stream a stringified resprenstation of the entire watson speech api response, and not just the transcript. Perhaps instead of the current code line - 
self.push(data.results[0].alternatives[0].transcript, 'utf8');

Could be modified to -

self.push(JSON.stringify(data.results[0]), 'utf8')

**Comment by nfriedly** [comment]
Hi @vondiplo,

I don't think we're going to implement a breaking API change like that, but it should be possible to get what you want with the `result` event and a custom [Readable Stream](https://nodejs.org/api/stream.html#stream_readable).

Also, just FYI, I have plans to merge in the [RecognizeStream changes from the Speech JS SDK](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js), so at that point there will be an `objectMode` option which will cause it to emit JSON objects instead of text. Then it will be even simpler to get the result that you're going for.

(The `result` event will then be marked as deprecated, but we'll still keep it around until at least the next major version release.)
