### ISSUE TITLE
[speech-to-text] Change createRecognizeStream() defaults to match service defaults

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/node-sdk#257]
The createRecognizeStream() method currently hard-codes parameter values.  Lines 72 through 81 of https://github.com/watson-developer-cloud/node-sdk/blob/master/services/speech_to_text/recognize_stream.js are as follows:

```
 var openingMessage = extend({
    action: 'start',
    'content-type': 'audio/wav',
    continuous: true,
    interim_results: true,
    word_confidence: true,
    timestamps: true,
    max_alternatives: 3,
    inactivity_timeout: 600
  }, pick(options, OPENING_MESSAGE_PARAMS_ALLOWED));
```

These settings override whatever the user passes in via the parameters of the method.  We need to eliminate the hard-coding and honor the params value passed by the caller.

**Comment by jeffpk62** [comment]
Nathan, you are correct about overrides:  I can override the hard-coded settings by setting the parameters to their default values.  In the SDK, we shouldn't turn on anything unless requested by the user to conform to the expected default behavior for the service.  With no param values, the user should expect the same default behavior from all interfaces.

I did more testing with the audio formats, and there is something odd going on.  With the recognize() method, if I set the content_type to audio/wav and send a .flac file, I get the following error:

```
{ code_description: 'Bad Request',
  code: 400,
  error: 'unable to transcode data stream audio/wav -> audio/x-float-array ' }
```

But doing the same thing with createRecognizeStream() produces successful results, as if I'd not set a content_type that differs from the actual type of the input file.

**Comment by nfriedly** [comment]
I think this change may have to wait until v3 is published, but fair enough. I don't have an exact date, but I'm thinking sometime in the next few months. (It'll have a few breaking changes, the largest of which will be geared towards working in web browsers.)

The browser Speech JS SDK is more reserved here, it enables `continuous` by default because I've seen a lot of confusion around that param (so much so that believe it may be removed entirely, or at least have the default changed in a future version of the service), and it enables `interim_results` because otherwise the service seems to be buffering all results to the end otherwise (even over websockets - which basically defeats the purpose of websockets).

**Comment by jeffpk62** [comment]
I thought we might wait until v3 for this, which is unfortunate but understandable from a resource and scheduling perspective.  I was still hoping we could quickly address the issue by removing the settings, but you're more aware of he ramifications of that than I am.  I'm also aware of the async and Builder changes coming in v3; I just can't address them at this time for a variety of reasons related to schedules and the state of the SDK..

I understand your points about continuous and interim results, but I would still recommend strongly not changing any of the default behavior via the SDK.  The SDKs should really be just alternative, simplified ways of calling the service APIs.  If we change default behavior, they become something more, and that's potentially pretty confusing, not just from a documentation perspective, but for users as well.  The service really does delay sending final results until they're done, which is the expected and documented behavior.  And there are other advantages to using WebSockets and to using the SDKs themselves.

I'm still unsure what's going on with the audio format specification; that one's we should look into.  If these are being parsed from file extensions, ignoring the content_type, we need to document that difference.  The difference in default behavior is too problematic or me to try to address at this time.

**Comment by jeffpk62** [comment]
Nathan, the Node SDK is still changing the default behavior of the service.  This really should not happen; it makes the SDK inconsistent with the default service, resulting in unexpected behavior for the user.  For example, to prevent interim results, I need to explicitly set the interim_results parameter to false, which is the opposite of how the Speech to Text service works.  This really isn't an enhancement request; the need to restore the expected default behavior is a defect.

**Comment by nfriedly** [comment]
Yes, I'm going to put things on the service defaults in v3.0. I should be working on that next sprint. There's an internal ticket to track it that links back here: https://github.ibm.com/Watson/developer-experience/issues/1034

**Comment by jeffpk62** [comment]
OK, thanks.  Having non-standard defaults is really cumbersome for the documentation, and every time I test with the SDK after some time away from it, I spend cycles trying to understand why I get unexpected results; there are probably users who wonder the same thing.

**Comment by nfriedly** [comment]
Alright, I believe the defaults in https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js are correct (and match the service defaults), and since we're saving this for a major release any way, I think it makes sense to merge in any code from the browser SDK that could be shared with the node SDK:

From https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/speech-to-text I believe the following files should be copied to the Node SDK, replacing the existing recognize-stream.js:

* content-type.js 	
* format-stream.js 
* no-timestamps.js 
* recognize-stream.js 	
* speaker-stream.js
* timing-stream.js 
* to-promise.js

The associated [tests](https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/test) should also be coppied over at the same time.

Once the node sdk v3 is released, the browser SDK should get a followup release where those files are removed from that codebase and instead loaded from the node.js codebase. It may make sense to keep the tests there for now to ensure they continue to work in browsers.

**Comment by nfriedly** [comment]
Oh, and copy https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/recognize_stream.js#L287 to https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/content-type.js#L16

**Comment by nfriedly** [comment]
This should also be copied to the browser js file:

https://github.com/watson-developer-cloud/node-sdk/blob/144a709c791db0866ceb94f364d5f79e82798952/speech-to-text/recognize_stream.js#L269

**Comment by ammardodin** [comment]
This will be resolved in the upcoming release since we're going off the official spec. Closing.
