### ISSUE TITLE
[solr-config] "A text field with defaults appropriate for English"

### ISSUE THREAD

**Issue by fernandomatheus** [watson-developer-cloud/node-sdk#281]
Anyone knows how to configure the schema.xml, solrconfig.xml files to another language?

**Comment by germanattanasio** [comment]
I think this is a Solr question @fernandomatheus. If you don't know how to create the `schema.xml` file start with this https://wiki.apache.org/solr/SchemaXml.
I think the Retrieve and Rank service supports schema-less collections. Take a look at https://cwiki.apache.org/confluence/display/solr/Schemaless+Mode

I'm closing this since it's not related to the node-sdk. Feel free to re-open it if I'm wrong.
