### ISSUE TITLE
Add timeout to a call

### ISSUE THREAD

**Issue by smhgit** [watson-developer-cloud/node-sdk#317]
HI,

request support timeout for a call and it will be good if user can set this time out value when calling a service.

https://github.com/request/request#http-authentication

timeout - Integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request. Note that if the underlying TCP connection cannot be established, the OS-wide TCP connection timeout will overrule the timeout option (the default in Linux can be anywhere from 20-120 seconds).

**Comment by smhgit** [comment]
HI,

request support timeout for a call and it will be good if user can set this time out value when calling a service.

https://github.com/request/request#http-authentication

timeout - Integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request. Note that if the underlying TCP connection cannot be established, the OS-wide TCP connection timeout will overrule the timeout option (the default in Linux can be anywhere from 20-120 seconds).

**Comment by nfriedly** [comment]
Hey, I didn't realize this until yesterday, but it is actually possible with the current version of the SDK - because all options pass to the constructor are passed along as defaults to the `request()` call - so, if you do something like this:

```js
var VisualRecognitionV3 = require('watson-developer-cloud/visual-recognition/v3');
var fs = require('fs');

var visual_recognition = new VisualRecognitionV3({
  api_key: '<api_key>',
  version_date: '2016-05-19',
  timeout: 15*1000// milliseconds; 15*1000 = 15,000ms = 15 seconds
});

var params = {
  images_file: fs.createReadStream('./resources/car.png')
};

visual_recognition.classify(params, function(err, res) {
  if (err)
    console.log(err);
  else
    console.log(JSON.stringify(res, null, 2));
});
```

This will fail with an `ETIMEDOUT` error if the request takes > 15 seconds.

The only gotcha is that this applies to every request sent through that instance. But creating an instance of VisualRecognitionV3 is relatively cheap, so you can just create a new one each time if you do need different timeouts.

I can't guarantee that this trick will always work, but it should work for at least the current 2.x branch, and the upcoming 3.x release. And, I'll try to have an alternate option in place if I do end up dropping it.

So, I'm going to go ahead and close this for now.

**Comment by layne00** [comment]
which line of code are we assigning options to default request calll? 
is it 
`options.jar = request.jar();`
in line 65 of base_service.js in lib/?
I don't see how the timeout parameter gets attached to request call.

**Comment by nfriedly** [comment]
No, you do not need to modify the source code of this library. You can pass a `timeout` param, set to the desired length in milliseconds, to the constructor when you create your instance. This will be passed along to the underlying `request` library.

**Comment by villasv** [comment]
Is this still valid, and for every of the services? I'm interested in the `NaturalLanguageUnderstandingV1` case, in particular.

This deserves to be documented somewhere, it seems pretty important to the SDK users.

**Comment by anweshan** [comment]
@villasv Yes, this still works for every service. This is because this isn't a feature in the SDK, rather in the NodeJS `request` library which has a `timeout` parameter. So when you create a service in our SDK it still will save any parameters like `timeout` you pass into the constructor, and when you call requests it will pass on `timeout`. Good idea on adding some more documentation on this if it isn't that clear to users already, I can add that.
