### ISSUE TITLE
[text-to-speech] No way of handling errors correctly before a pipe to the FS

### ISSUE THREAD

**Issue by deanc** [watson-developer-cloud/node-sdk#368]
# Steps to reproduce

Pass in some bad params to the `synthesize` function e.g.
```
    var params = {
        text: "Hello world",
        voice: "asdf", // bad voice...
        accept: 'audio/ogg'
    };
```

# Expected behavior:

Should be able to catch some kind of error before piping. For example:

```
text_to_speech.synthesize(params)
        .on("error", function (err) {
            console.log(err); // this should prevent the pipe from ever being reached
        })
        .pipe(fs.createWriteStream(destinationPath + "/" + hash + '.ogg'));
```
# Actual behavior
The error is never emitted, and the file is always written to the FS.

# Node version
7.3.0

# SDK version
```"watson-developer-cloud": "^2.14.4"```

# Summary

As it stands errors are sent as JSON, meaning the error itself is written to the file system. This is not ideal. Please advise.

**Comment by nfriedly** [comment]
Hi @deanc 

I agree that this is not ideal behavior for the streaming API. The SDK currently uses [request](https://www.npmjs.com/package/request) under the hood which suffers from the same issue. 

That said, your desired behavior is possible with a couple of tweaks to your code:

```js
var stream = textToSpeech.synthesize({
  text: 'Hello from IBM Watson',
  voice: 'INVALID_VOICE', // comment this line to show the example working correctly
  accept: 'audio/wav' // default is audio/ogg; codec=opus
}, function(error) {
  if (error) {
    console.log(error);
  }
})
.on('response', function(res) {
  if (res.statusCode === 200) {
    stream.pipe(fs.createWriteStream('output.wav'));
  }
  // errors will be handled by the callback after the body is downloaded
});
```

This works by hooking into the `response` event that request provides. This event is always emitted before any data, and thus is a safe way to check the status code and headers before piping the output. 

I also put a copy of this in https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/text_to_speech_synthesize_handle_errors.js

I'll also look into improving the streaming API to emit error events instead of streaming the data for non-200 statuses, but I'm not sure if/when that would be implemented.

**Comment by deanc** [comment]
Hi @nfriedly . Thanks for the reply!

I ended up going down the route of checking the response status code as well as the returned mime type. So this is line with your proposed solution.

However, there are other errors that can occur. For example, what if there is no connection at all. There is no way of setting a timeout value using the SDK as far as I can see. To test this use your example, but turn off your network. The node process appears to time out.

**Comment by nfriedly** [comment]
Hum, I just tried it with wifi off and quickly got this error:

```
{ Error: getaddrinfo ENOTFOUND stream.watsonplatform.net stream.watsonplatform.net:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'stream.watsonplatform.net',
  host: 'stream.watsonplatform.net',
  port: 443 }
```

(basically a DNS error.)

You're getting a timeout if you run text_to_speech_synthesize_handle_errors.js with no network connection?
