### ISSUE TITLE
[visual-recognition] URL image classify with multiple values in params.classifier_ids array does not work as expected

### ISSUE THREAD

**Issue by dtom90** [watson-developer-cloud/node-sdk#411]
The VisualRecognitionV3 classify function comment specifies on [line 228](https://github.com/watson-developer-cloud/node-sdk/blob/master/visual-recognition/v3.js#L228):
```javascript
/** @param {Array} [params.classifier_ids=['default']] An array of classifier IDs to classify the images against.
```
But when we try to classify a URL image with two classifiers passed an array of two strings, e.g.:
```javascript
var classifier_ids = [
  'churches_1530442909',
  'default'
];
```
we only get the default classifier results. 

However, if we specify only our custom classifier:
```javascript
var classifier_ids = ['churches_1530442909'];
```
Then we do see the results of the custom classification.
This only occurs with URL image (GET) classifications, not image file (POST) classifications. 

I believe the error is somewhere in the request builder (possibly `requestwrapper.js`) in which the code is not taking the classifier_ids array of strings and converting to a single string of comma-separated values for the GET request. 
To prove this point, the following array of a single string value containing comma-separated classifier_ids passed into the function works as expected:
```javascript
var classifier_ids = [ 'churches_1530442909,default'];
```
Passing this into the classify method returns the results of both classifications.

**Comment by nfriedly** [comment]
Hi @dtom90,

Thanks for the report! This should be fixed in v2.23.1 once the CI loop finishes. 

The default behavior for the underlying request library that we use is to turn arrays into repeated arguments when in a querystring, rather than joining them into a single comma-seperated value. 

It's a sane default but obviously not what the Visual Recognition service expects, so I created a helper method that all VR calls now go through which encodes things the way the service wants, fixing your issue and a couple of similar ones that I identified. 

It also has a couple of tests now.
