### ISSUE TITLE
[speech-to-text] Getting bad request when running the example

### ISSUE THREAD

**Issue by manigurusankar10** [watson-developer-cloud/node-sdk#450]
I ran the `speech_to_text.v1.js` nodejs app and got the following error:

`
{
  "code": 400,
  "code_description": "Bad Request",
  "error": "Malformed GUID: 'd83aa3c0-bd6f-11e6-acaa-019f979b8xyz'"
}`

It still displayed the `results`, `data`, and `close` events after the above error.

I checked the API for speech to text and saw that 400 error is an invalid user input but it seems that is not the case since the app still runs after getting that error.

**Comment by nfriedly** [comment]
That's the guid for a customization, but customizations are tied to your account. The one listed in the example is owned by someone else, so you aren't allowed to use it.  

It still "worked" because the example file is doing two different things and the other one did work.

I'm going to update it to remove that guid and make it more clear that you have to create and add your own.

**Comment by nfriedly** [comment]
Actually, that was only about 1/4 of a customization example, so I just removed it for now. An incomplete example that starts in the middle is probably less helpful than no example at all. I'll try and find some time to write a complete STT customization example eventually, but the integration tests can serve as a good guideline in the meanwhile.
