### ISSUE TITLE
[discovery] error while querying collection using return parameter

### ISSUE THREAD

**Issue by varun5001** [watson-developer-cloud/node-sdk#591]
While querying a collection if i use return parameter like, `return: ['enriched_text, extracted_metadata']`
the response is 

> TypeError: _params.return.split is not a function . 

This is issue for SDK > 3, but where as for SDK < 3 the response is returned with specified fields.

**Comment by ammardodin** [comment]
@varun5001 Thanks for reporting the issue. I see where the problem is and I will push a fix later on today. As a workaround for now, either use the parameter `return_fields` with the same value you have above ['enriched_text, extracted_metadata'], or use `return` with a sting like this `enriched_text, extracted_metadata`.

**Comment by varun5001** [comment]
@ammardodin if i use a string return: 'enriched_text, extracted_metadata', then the response is returned with with only first value in the string. In this case the response is returned with only enriched_text values

**Comment by ammardodin** [comment]
@varun5001 So when you were using the parameter as `return: ['enriched_text, extracted_metadata']` in the previous release of the SDK, you were getting the expected response ? I think the problem might be that if there are multiple values for the return query parameter, the service ignores the rest unless we send the values for that parameter as a comma separated string. I will make sure to include this in the fix.

**Comment by varun5001** [comment]
@ammardodin yes it was working as expected for versions < 3.
