### ISSUE TITLE
[Conversation]WorkspaceExport type has some differences to the workspace.json retrieved via getWorkspace with export = true 

### ISSUE THREAD

**Issue by RoxanaDevIBM** [watson-developer-cloud/node-sdk#642]
While converting a script to TypeScript that downloads a conversation workspace to be stored locally, I have found some differences between the JSON received and the types described in v1-generated.

Consider the following example:
```javascript
ConversationServiceUtils.getWorkspace(conversation, { workspace_id: wrokspaceID, export: true }).then(
  (response: ConversationV1Types.WorkspaceExport) => {
    if (response.intents) {
      response.intents[0].intent; //Error, actual workspace type
      response.intents[0].intent_name; //Correct type based on v1-generated
    }
  }
);
```
The first `response.intents[0]` line from above, would cause a type error as IntentExport is define as following:
```javascript    
interface IntentExport {
        /** The name of the intent. **/
        intent_name: string;
        /** The timestamp for creation of the intent. **/
        created: string;
        /** The timestamp for the last update to the intent. **/
        updated: string;
        /** The description of the intent. **/
        description?: string;
        /** An array of user input examples. **/
        examples?: Example[];
    }
```
While in the actual returned JSON the content is:
```
  "intents": [
    {
      "intent": "selections",
      "created": "2018-02-22T12:01:11.852Z",
      "updated": "2018-02-22T12:01:11.852Z",
      "examples": [
        {
          "text": "what options do ypu have?",
          "created": "2018-02-22T12:01:11.852Z",
          "updated": "2018-02-22T12:01:11.852Z"
        }
      ],
      "description": null
    }]
```
The same issue is happening with (as far as what I am working on goes):
interface Example - example_text --> text
interface DialogNode - dialog_node_id --> dialog_node
interface EntityExport - entity_name --> entity
interface ValueExport - value_text --> value

A solution would be to rename those properties to match the workspace returned by getWorkspace. 

Can this be some version mis-match? The latest workspace I tested on, is the sample workspace created when adding conversation service to project.

Thanks in advance for the help!

**Comment by anweshan** [comment]
What version are you using of the SDK?

My first thought is perhaps this is due to the fact that we have adapters - so we have typescript code that maps variable names that older versions of the sdks used to the generated versions variable names, to avoid breaking changes. But I will look into this more!

**Comment by ammardodin** [comment]
@RoxanaDevIBM The interfaces are actually generated based on the service API definitions. We have some alternate names as you see in the conversions above, which are done with hopes of providing clarity. For instance, for the `IntentExport` if we use `intent` instead of `intent_name`, we create ambiguity because it's not clear whether `intent` refers to some object or if it's the actual name of the intent.

**Comment by anweshan** [comment]
So this isn't actually an issue, as this was done intentionally - so I am closing this issue.
