### ISSUE TITLE
Inconsistency between SDK and API documentation for version date setting for Assistant API

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/node-sdk#682]
Conversation accepted `version_date` as the API version, but the API for Assistant is now looking for `version`. 

There is however a discrepancy with the API documentation which refers to `version_date`.
https://www.ibm.com/watson/developercloud/assistant/api/v1/node.html?node
Either the API documentation or the SDK is in error.

**Comment by germanattanasio** [comment]
Hi @chughts you are right.

* The API only accepts a `version` parameter
* The Node SDK accepts a `version`(new) and `version_date`(old and deprecated)
* The API Reference uses the old `version_date` rather than the new `version` parameter in the constructor.

We will update the documentation to match the API and use `version`. You should use `version` introduced in v3.0.0

I'm going to close the issue since it's not a problem in the SDK and ask the documentation team to update the API Reference.
