### ISSUE TITLE
[conversation] => `updateValue`: Error: 'Patterns are defined but type is not specified.'

### ISSUE THREAD

**Issue by catcher-in-the-try** [watson-developer-cloud/node-sdk#750]
It appears that any call to the `updateValue` method of Conversation will fail, unless the `new_type` parameter is specified.

Code that doesn't work:

```
      let params = {
        workspace_id: '<redacted>',
        entity: 'myEntityType',
        type: 'patterns', // tried with and without this line
        value: 'myCanonicalValue',
        new_patterns: ['test'],
      };

      watsonApi.updateValue(params, (error, response) => {
        if (error) {
          console.log('Error returned by Watson when updating an entity value.');
          reject(error);
        } else {
          resolve(response);
        }
      });
```

The error is:

```
[ { message: 'Patterns are defined but type is not specified.',
       path: '.patterns' } ],
```

Workaround: add `new_type: "patterns"` for each request, even if the type didn't change.

Details on StackOverflow: https://stackoverflow.com/q/51471227/6269864

**Comment by dpopp07** [comment]
Thanks for the issue, I will look into it.

**Comment by dpopp07** [comment]
Hi @catcher-in-the-try, this is actually intended behavior, also the documentation could certainly be more clear.

The body params for this operation in the Node SDK are
- new_value,
- new_metadata,
- new_type,
- new_synonyms,
- new_patterns

So while the service takes a `type` parameter, the Node SDK takes a `new_type` parameter and translates that into `type` before sending the request. That's why adding
> type: 'patterns', // tried with and without this line
did not help. You just need to use `new_type` to specify when you are using patterns. We can't hard code this value in the SDK because the default still needs to be `synonyms`. 

There are some internal reasons why this parameter got named `new_type` that make sense for other methods, but not this one. I will open an issue to change these into more appropriate parameter names but since that will introduce a breaking change, it will not be available until the next major release.

Let me know if this answers your question or if you have additional feedback. Thanks again

**Comment by catcher-in-the-try** [comment]
@dpopp07 I think it would just make sense to clarify the docs to show that this parameter is required. And close this one. Cheers!

**Comment by dpopp07** [comment]
Sounds good!

**Comment by dpopp07** [comment]
For reference: the parameter names for Node have been documented here https://www.ibm.com/watson/developercloud/assistant/api/v1/node.html?node#update-value
