### ISSUE TITLE
[discovery] Angular2 build fails on require sdk

### ISSUE THREAD

**Issue by elvisgn** [watson-developer-cloud/node-sdk#770]
Hi,
I've created an angular v6 app in node v8.11.3. The app builds smoothly without any code change. The moment I add watson sdk and include the discovery require statement, build fails.

**SDK Version:**
Node v8.11.3
Npm 6.4.0
Angular 6.1.0
Watson-developer-cloud 3.9.0

**Steps to reproduce:**
1. Create `ng new demo`
2. `npm install watson-developer-cloud`
3. Add statement `var DiscoveryV1 = require('watson-developer-cloud/discovery/v1')` in app.component.ts
4. Fix the ' Cannot find name require' error by updating "types": [ "node" ] in tsconfig.app.json
5. `ng build --prod`

**Expected behavior:** Build should work without errors

**Actual behavior:** Receiving error
```
ERROR in ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in '/Users/gbmmobility/Documents/MobileProjects/watson-services/node_modules/aws-sign2'
ERROR in ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in '/Users/gbmmobility/Documents/MobileProjects/watson-services/node_modules/aws4'
-- truncated --
ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/gbmmobility/Documents/MobileProjects/watson-services/node_modules/forever-agent'
ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/gbmmobility/Documents/MobileProjects/watson-services/node_modules/tunnel-agent'
ERROR in ./node_modules/watson-developer-cloud/node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in '/Users/gbmmobility/Documents/MobileProjects/watson-services/node_modules/watson-developer-cloud/node_modules/request'
```

**Comment by dpopp07** [comment]
Hi @elvisgn, it turns out this is intended behavior in Angular 6 ([this comment explains it really well](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814)). The Node SDK has some dependencies that use Node-only modules like `fs`, `http`, etc. These are not supposed to work in the browser. There are workarounds for this, but Angular seems to have dropped support for these workarounds in major version 6.

We are hoping to make this SDK more browser-friendly in the future. For now, please see the [webpack example](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack) (or maybe the [browserify example](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/browserify)) to see if integrating these into your build somehow would solve the issue.

Let me know if you have any more questions or if that approach is doable or not.

**Comment by dpopp07** [comment]
Hi @elvisgn, do you have an update on this?

**Comment by elvisgn** [comment]
Hi @dpopp07, you were right about the behavior in Angular 6. I moved the require out of the component and into an express middleware layer. It works now.
