### ISSUE TITLE
AssistentV1 doesn't return expected response object

### ISSUE THREAD

**Issue by JeroenBodart** [watson-developer-cloud/node-sdk#785]
I'm sending an initial request with the AssistentV1 service to trigger the 'welcome' of my Watson Chatbot. The response contains a list of options that is defined in the property generic. When calling from the chatbot itself it shows the expected result but in my application the response doesn't contains the expected property or options.

At the moment I'm using the sdk version v3.11.1.

Documentation location: http://watson-developer-cloud.github.io/node-sdk/master/interfaces/assistantv1.outputdata.html#generic

### Watson response:  
![2018-10-03 16_46_15-microsoft edge](https://user-images.githubusercontent.com/14278720/46418352-e7b94500-c72b-11e8-8898-c6d3c34781d0.png)

### Application response:
![2018-10-03 16_47_58-app js - build2018-intake-conversation - visual studio code](https://user-images.githubusercontent.com/14278720/46418486-2818c300-c72c-11e8-806b-cb46848450e6.png)

**Comment by dpopp07** [comment]
Hi @JeroenBodart 
What method are you calling with the SDK and what parameters are you providing?

**Comment by dpopp07** [comment]
@JeroenBodart Ah yes, thanks for posting that code. I believe your problem is that you're using an older version of the service and the UI is using the current version. The response structure has changed. Update your version date to `2018-10-04` to build your application on the version of the service that is available right now. Let me know if this does not solve your problem.

**Comment by JeroenBodart** [comment]
You're right! I was using the wrong version '2017-05-26' instead of '2018-10-04'. Thank you for your help.
