### ISSUE TITLE
Object is a wrong type for key-value pairs

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/node-sdk#880]
**Overview**
I am using Node-SDK in my Typescript project and I discovered that Object type is used in definition of many fields containing key-value pairs.
According to https://stackoverflow.com/questions/18961203/any-vs-object
> * any can be anything (you can call any method etc on it without compilation errors)
> * Object exposes the functions and properties defined in the Object class.

Specifically I am trying to check property of [DialogNodeAction.parameters](https://github.com/watson-developer-cloud/node-sdk/blob/v4.1.0/assistant/v1.ts#L4356)

When I try to check if a property exists, I get error: TS2339: Property 'xxx' does not exist on type 'Object'.

I think that it would be better to replace  all Objects with `{ [index: string]: any }` in type definitions.

**Expected behavior**
It works

**Actual behavior**
S2339: Property 'xxx' does not exist on type 'Object'.

**SDK Version**
4.1.0

**Additional information:**
- OS: WSL on Windows 10
- v10.15.3

**Comment by mkistler** [comment]
Can you show the exact code that is failing?

**Comment by Naktibalda** [comment]
Here is the minimal reproduction of this issue:

```typescript
import AssistantV1 = require('ibm-watson/assistant/v1');
import {MessageResponse} from "ibm-watson/assistant/v1";

const assistant = new AssistantV1({
    version: '2019-02-28',
});

async function main () {
    const response: MessageResponse = await assistant.message({
        workspace_id: 'test',
        input: {
            text: 'test'
        }
    });

    for (const action of response.actions) {
        console.log(typeof action.parameters.test);
    }
}

main();
```

Output:
```
$ node ./node_modules/typescript/bin/tsc
src/index.ts:18:46 - error TS2339: Property 'test' does not exist on type 'Object'.

18         console.log(typeof action.parameters.test);
                                                ~~~~


Found 1 error.
```

**Comment by mkistler** [comment]
What is wrong with just changing that line to:
```
        console.log(typeof action.parameters['test']);
```

**Comment by Naktibalda** [comment]
It is an unnatural way of accessing object property, so it won't be anyones guess.

**Comment by mkistler** [comment]
But making the change to define `parameters` as a map will force you to use this syntax anyway, right?

**Comment by Naktibalda** [comment]
No, a map with string keys is an object in javascript, so `.name` syntax works.

**Comment by mkistler** [comment]
This is really confusing. Typescript disallows `params.test` when `params` is defined as an `Object`, but allows `params.test` when `params` is defined as `{ [key: string]: any; }`, based on the reasoning that "a map with string keys is an object in javascript".  Does that mean that an `Object` is _not_ an object in javascript?

Also frustrating is that the Typescript docs are extremely difficult to navigate and search. I can't find where the syntax and behavior of map types are described anywhere.

I did run across [this post](https://www.bennadel.com/blog/3126-object-access-bracket-notation-vs-dot-notation-with-typescript-in-angular-2-rc-4.htm) from 2016 which shows the behavior that _I_ would have expected -- namely that tsc throws an error on dot-notation for a map with string keys.  I see that's no longer true, but I fail to understand why.

**Comment by Naktibalda** [comment]
I would like to point out that this syntax is used in 12 different places already:
https://github.com/watson-developer-cloud/node-sdk/blob/v4.1.0/assistant/v1.ts#L4232

**Comment by Gerrit0** [comment]
TypeScript has come a long way since 2016. Both styles of property access described in that post work in TS 2.4.1 (oldest TS version I have on hand), and we are now on TS 3.4.4.

I believe you misunderstood the `Object` type. Typing a variable as `Object` says `typeof thisVar === "object"`. It says absolutely nothing about the keys of `thisVar` besides the keys common to all objects like `.hasOwnProperty`. (Also, don't use `Object`, if you must, use `object` - [docs](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html))

`{ [key: string]: any }` describes an indexed type ([docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types-and-string-index-signatures)) which accepts any string key (and also numbers as `a[1]` is equivalent to `a["1"]`) and whose properties are typed as `any`. If you aren't a fan of the syntax, you can also describe an object with arbitrary `string` keys and `any` as values with `Record<string, any>`.

I assume by "map" types you actually mean [mapped types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types). The `{ [k: string]: any }` syntax doesn't describe a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). Mapped types are a bit different from index types. Mapped types are used to transform an existing type by "mapping" over its keys.

I unfortunately have to agree that the TypeScript docs are severely lacking in usability. Quite a few of the really interesting features are only really described in the release notes for the version they were added in. Basarat's TypeScript book is a good resource for most features, though it doesn't describe everything. You might find the page on [Index Signatures](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html) to be helpful.
