### ISSUE TITLE
ibm-credentials.env could pick up WORKSPACE_ID and SKILL_ID

### ISSUE THREAD

**Issue by scottdangelo** [watson-developer-cloud/node-sdk#931]
Since `ibm-credentials.env` picks up the ENV variable for the service IAM_AKIKEYs , it would be very useful if it also picked up WORKSPACE_ID and SKILL_ID and exported them to the environment.
These are often needed in an app, so they must be pushed to the environment anyway, i.e. by putting in a `.env` file.
It's kind of clunky to have to put one ENV variable in a `.env` and the others in `ibm-credentials.env`.

**Comment by dpopp07** [comment]
> It's kind of clunky to have to put one ENV variable in a .env and the others in ibm-credentials.env.

That's reasonable. We are currently re-designing the way we handle authentication for v5 so I can look at factoring this in to that design.

That said, the SDK supports reading credentials automatically from a standard `.env` file. So you can just put everything there and as long as you load them with a package like [`dotenv`](https://www.npmjs.com/package/dotenv). Would that address your use case?

Otherwise, there are some challenges to implementing this. We do all the credentials processing in a separate package, `ibm-cloud-sdk-core`. That's where we read in the credentials file and it has no knowledge of the service-level options.

**Comment by scottdangelo** [comment]
Yes, we can use the .env file for credentials, and that's actually how we do it. It just means we cannot teach our users about the ibm-credentials.env method.
FYI, I and my team work in developer advocacy, creating content for developer.ibm.com and for use by advocates at workshops and customer sites. So, this is just a nice-to-have, not a must, and mainly is so we can demonstrate it.
Thanks.
